### ISSUE TITLE
feat: TimeTable 컴포넌트에 로직을 구현한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#12]
## Description 🔍

TimeTable 컴포넌트에 state와 로직을 연결하여 구현합니다.

datas: 백엔드로부터 불러온 데이터를 전달합니다.
startDate: 기준점으로 삼을 시작 날짜를 지정합니다.
disabledRanges: 비활성화할 날짜 영역을 지정합니다.

## TODO ✅

- [ ] datas 전달 구현
- [x] startDate 전달 구현
- [x] disabledRanges 전달 구현

## References 🗂️

>  없음

**Comment by PortalCube** [comment]
#18 에서 일부 구현

**Comment by PortalCube** [comment]
로직 부분 issue 분리로 closed
