### ISSUE TITLE
feat: 대기중인 밥약 목록 페이지의 API 연결을 진행한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#35]
## Description 🔍

대기중인 밥약 목록 페이지의 API 연동 작업을 진행합니다.

## TODO ✅

- [ ] WaitBab 페이지에서, getEvents 함수로 response를 받아온 다음 해당 데이터를 states에 저장하는 부분을 구현한다.
- [ ] API 명세에 따라 getEvents 함수를 구현한다.
- [ ] API 명세와 컴포넌트가 사용하는 데이터 스키마가 다르다면, WaitBab 페이지에서 스키마를 변환하는 함수를 구현하거나 WaitBox를 뜯어고친다.

## References 🗂️

https://www.notion.so/4a9d94c238f4494e8a705de143f1c392?pvs=4
