### ISSUE TITLE
feat: 밥약 만들기 페이지의 API 연결을 진행한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#37]
## Description 🔍

밥약 만들기 페이지의 API 연동 작업을 진행합니다.

## TODO ✅

- [x] DatePicker 컴포넌트에서 상태가 변경되었을 때 onChange props로 전달된 함수를 호출하도록 구현
- [x] CreateEvent 페이지에 상태 값을 저장하는 로직 구현
- [x] API 명세에 따라 createEvent 함수를 구현하고 response 를 처리하는 로직 구현
- [x] ShareBab 페이지를 response에서 받은 공유 링크와 함께 열기

## References 🗂️

https://www.notion.so/40794cb02985445984dada9eee4a0d7b?pvs=4

**Comment by PortalCube** [comment]
#37 에서 임시 연결 완료
로그인 API 구현 및 백엔드 API 테스트 후 close
