### ISSUE TITLE
feat: 대기중인 밥약 페이지의 API 연결을 진행합니다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#38]
## Description 🔍

대기중인 밥약 페이지의 API 연동 작업을 진행합니다.

## TODO ✅

- [x] PendingParty 페이지에서, TimeTable 컴포넌트에 값을 props로 전달하는 부분을 구현한다.
- [x] PendingParty 페이지에서, TimeTable 컴포넌트의 readOnly 값을 UI로 변경하는 부분을 구현한다.
- [x] PendingParty 페이지에서, getEvent 함수와 getTimeTable 함수로 response를 받아온 다음 해당 데이터를 state에 저장하는 부분을 구현한다.
- [x] API 명세에 따라 getEvent 함수와 getTimeTable를 구현한다.
- [x] PendingParty 페이지에서 postTimeTable 함수와 postEventConfirm 함수로 데이터를 전송하는 로직을 구현한다.
- [x] API 명세에 따라 postTimeTable 함수와 postEventConfirm 함수를 구현한다.

## References 🗂️

[getEvent](https://www.notion.so/bb2333c871de4f61a88a3b0445deab9b?pvs=4)
getTimeTable -> 백엔드에서 작성중
[postTimeTable](https://www.notion.so/42a29c919cc64acaaae52c68b228a302?pvs=4)
[postEventConfirm](https://www.notion.so/271a95e0c9fc44a1b7e9ce57b350f945?pvs=4)

**Comment by PortalCube** [comment]
#50 에서 완료

최종 테스트 대기중
