### ISSUE TITLE
feat: 확정된 밥약 페이지의 API 연결을 진행한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#39]
## Description 🔍

확정된 밥약 페이지의 API 연동 작업을 진행합니다.

## TODO ✅

- [x] ScheduledEvent 페이지에서, getEvent 함수로 response를 받아온 다음 해당 데이터를 state에 저장하는 부분을 구현한다.
- [x] API 명세에 따라 getEvent함수를 구현한다.
- [x] ScheduledEvent 페이지에서, 송금 정보를 입력하는 UI와 state를 연결한다.
- [x] ScheduledEvent 페이지에서 postEventFinish 함수로 데이터를 전송하는 로직을 구현한다.
- [x] API 명세에 따라 postEventFinish 함수를 구현한다.

## References 🗂️

[postEventFinish](https://www.notion.so/28e0b563bfd84e74889f5bb55d1e4078?pvs=4)

**Comment by PortalCube** [comment]
#46 에서 구현 완료

로그인 API 및 백엔드와의 최종 연결 테스트 후 close
