### ISSUE TITLE
feat: 종료된 밥약 페이지의 API 연결 작업을 진행한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#40]
## Description 🔍

종료된 밥약 페이지의 API 연동 작업을 진행합니다.

## TODO ✅

- [x] Payment 페이지에서, getEvent 함수로 response를 받아온 다음 해당 데이터를 states에 저장하는 부분을 구현한다.
- [x] API 명세에 따라 getEvent 함수를 구현한다.
- [x] API 명세와 컴포넌트가 사용하는 데이터 스키마가 다르다면, Payment 페이지에서 스키마를 변환하는 함수를 구현하거나 Payment 페이지를 뜯어고친다.

## References 🗂️

https://www.notion.so/bb2333c871de4f61a88a3b0445deab9b?pvs=4
