### ISSUE TITLE
feat: 배포를 진행한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#41]
## Description 🔍

프론트엔드 결과물을 작업물을 웹으로 배포합니다.

## TODO ✅

- [x] 배포 방식 결정
- [x] 배포 절차 준비 및 진행 (도메인 구비, HTTPS 세팅, 리다이렉션, 기타 등등..)
- [x] 최종 배포 테스트
- [x] 해커톤 끝!

**Comment by PortalCube** [comment]
배포 종료

**Comment by PortalCube** [comment]
끝
