### ISSUE TITLE
feat: 로그인 & 로그아웃 기능 구현

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#42]
## Description 🔍

브라우저에 로그인 JWT 토큰을 저장하고, redux로 관리하는 기능을 구현합니다.

## TODO ✅

- [x] userSlice 최종 구현
- [x] cookie로 브라우저에 JWT 토큰 저장하는 부분 구현
- [x] 로그인 API 연결
- [x] 최종 테스트

**Comment by PortalCube** [comment]
최종 테스트 제외 #48 에서 완료
