### ISSUE TITLE
feat: 읽기 전용 시간표 컴포넌트를 구현한다.

### ISSUE THREAD

**Issue by PortalCube** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_11_FE#7]
## Description 🔍

입력 용도의 타임 테이블 컴포넌트가 아닌, 읽기 용도의 타임 테이블 컴포넌트 구현하기
(밥약 확정 이후 각 참가자들의 가능 시간을 확인 할 때 사용)

## TODO ✅

- [x] 기존 타임 테이블 컴포넌트를 UI MouseEvent를 제거하고 새롭게 분리
- [x] 각 item의 데이터에 따라 테이블 item 색상 값 조절
- [ ] (어쩌면 구현) item에 마우스 커서 올리면 누가 해당 시간에 투표했는지 tooltip 표시

## References 🗂️

>  아직 없음 (추후 추가)

**Comment by PortalCube** [comment]
#18 에서 완료
